# Generated by Django 5.2.1 on 2026-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_attendance_notes_graderecord_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['grade__level', 'name']},
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.IntegerField(default=0, verbose_name='الترتيب الأكاديمي'),
        ),
    ]
