# Generated by Django 5.2.1 on 2026-03-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_grade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name')},
        ),
    ]
