# Generated by Django 5.2.1 on 2026-03-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_number',
            field=models.CharField(blank=True, error_messages={'unique': 'رقم القيد هذا مستخدم بالفعل في النظام.'}, max_length=50, null=True, unique=True, verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(error_messages={'unique': 'هذا الصف موجود بالفعل.'}, max_length=50, unique=True, verbose_name='اسم الصف (مثال: الأول)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(error_messages={'unique': 'اسم هذه المادة موجود بالفعل.'}, max_length=100, unique=True, verbose_name='اسم المادة'),
        ),
    ]
